services:
    coolify:
        image: ghcr.io/coollabsio/coolify:latest
        container_name: coolify
        restart: always
        working_dir: /var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - coolify
        depends_on:
            - postgres
            - redis
            - soketi
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
    postgres:
        image: postgres:15-alpine
        container_name: coolify-db
        restart: always
        networks:
            - coolify
        volumes:
            - postgres_data:/var/lib/postgresql/data
    redis:
        image: redis:7-alpine
        container_name: coolify-redis
        restart: always
        networks:
            - coolify
    soketi:
        image: quay.io/soketi/soketi:latest
        container_name: coolify-realtime
        extra_hosts:
            - host.docker.internal:host-gateway
        restart: always
        networks:
            - coolify
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
networks:
    coolify:
        name: coolify
        driver: bridge
        external: false
volumes:
    postgres_data:
